### ISSUE TITLE
Add ability for CMEPS to handle ESMF location streams

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CMEPS#102]
I propose this primarily as a solution to #95 without requiring any changes to ESMF. But, I think it may hold value in and of itself primarily for CTSM to run with a list of scattered points. Running with a list of scattered points could be useful for other CESM components -- I'm not sure.

I think it might be more reasonable to do this in CMEPS than it is to require changes in ESMF. This would be using existing capability in ESMF and just extending a few CMEPS modules that already handle either ESMF meshes or grids, and allow them to also handle ESMF location streams.

I do see the ability to handle either a mesh or a grid in nuopc_shr_methods, field_getfldptr subroutine, where it checks for either one. For mizuRoute I think the alternative geometry may have to be a location stream. (ESMF_TYPEKIND_LOCSTREAM), which is valid from the ESMF view. The reason I think it might have to be a location stream is that it isn't any kind of regular grid, and once you remove the vertices -- it's essentially a set of random center grid coordinates, which is what a location stream is. 

I noted this in #95, but here's a summary again, looks like it would only involve:  nuopc_shr_methods.F90, med.F90 and med_methods_mod.F90:

> "I do see the ability to handle either a mesh or a grid in nuopc_shr_methods, field_getfldptr subroutine, where it checks for either one.
> ...
> realizeConnectedGrid/completeFieldInitialization in med.F90 has similar logic for GRID vs. MESH, as does med_methods_mod.F90 which has some methods for dealing with handling either GRID or MESH. So again could be extended to handle location streams. ESMF objects (such as Fields) can be built upon either GRID, MESH or location stream. So we could extend the ability of CMEPS to also handle location streams."

**Comment by ekluzek** [comment]
In searching the latest code on master for either geomtype or ESMF_GEOMTYPE the only instance I find that use it outside of the above mentioned is med_phases_ocnalb_mod.F90. But, since the need for this doesn't involve OCN or ATM I don't see that module would need to be changed. So only med.f90, med_methods_mod.F90 and nuopc_shr_methods.F90 would need to be modified.

**Comment by mvertens** [comment]
@ekluzek - this is not an appropriate solution for Mizuroute since you cannot regrid data to or from location streams conservatively. And conservative regridding of fluxes is a key requirement for CESM.

**Comment by ekluzek** [comment]
@mvertens I thought I made this clear, but what I'm suggesting is that offline mapping files would be used to do any of the regridding. Location streams can't take care of the mapping, but it can provide the grid locations, and offline maps can do the regridding. I think the offline mapping files can be coupled with the location streams -- unless I'm missing something.

Part of what I'm saying is that the time and memory requirements to read in the mesh is too long, much less to also create the regridding is too long. So to short circuit that I'd like to use location streams and offline mapping files to do the regridding. Does that make sense now?

The only other option that I see is to require a change from ESMF for them to add an option so that we don't read in the vertices for the mesh. Do you think that is the better solution?

**Comment by mvertens** [comment]
@ekluzek - Thanks for the clarification. There are several problems with what you are suggesting:

1. The CMEPS mediator is built assuming an underlying mesh. It can receive a grid through the connect and then that grid is transferred to a mesh. Its not clear to me what the effect would be of send a location stream through the connector (or if that is currently possible with NUOPC). The fact med_methods_mod and `nuopc_shr_methods` reference grids is unfortunate and needs to be cleaned up. This is just historical code.
2. In addition, `med_io_mod` assumes a mesh - the distgrid and the element coordinates are obtained directly from the mesh. These are needed in the creation of the mediator history and restart files.
3. `med_map_mod`.F90 also references a mesh for normalizing by fractions. You need to create a field bundle containing the fraction on the destination mesh to do the normalization. This is needed for mapping the land to the river - where you scale the fluxes by the land fraction.

So we could certainly explore this option and discuss this some more - but I don't think it will be a straightforward implementation. Furthermore, other modeling efforts (NOAA) are also using CMEPS so we need to make sure that whatever we introduce does not break their functionality.

**Comment by ekluzek** [comment]
OK, good to know. That's discouraging, but good to know. I look forward to brainstorming about solutions. It'll help to have the group of us to go over it from all the different angles.

**Comment by ekluzek** [comment]
An emerging possible answer to this is a simplified mesh that's used in a similar manner to this as a simple mesh to read in when mapping files are used. Naoki is making good progress in an automated way to simplify the mesh before running. The full complex mesh would be used to create the mapping files (either offline or as a separate step). 

A thing that might be awkward about that though is that there will have to be a different mesh file used when the mapping files are provided. so there might need to be some mechanism to pick the mesh file that's going to be used. I'm not sure how that would be done in an easy to do fashion.

**Comment by ekluzek** [comment]
OK, so we just met as a group. Naoki is having trouble with simplifying the mesh in an automated way that doesn't still have topology problems. But, we think the way forward is to do two things. 

A reasonable way to run with mizuRoute will be to use a simplified dummy mesh file, and a mapping file that goes with it with the mapping file created offline. The dummy mesh file can be really simple and just have four corners around a center coordinate. It doesn't really have to make much sense, we just need to specify the grid decomposition. Such a simple mesh could be easily read in, without high compute or memory requirements. And this simple mesh could create dist-grids and fields on top of it. with an offline mapping file to do the regridding. So that slides right in the system and is a way forward for the science we want to do.

Bob O. also talked about a possible solution in ESMF to ignore the vertices. But, we figure we don't really need that solution, when the plan is to use offline regridding anyway. So we don't think we'll ask for that.

Initially Naoki has a script from the National Water Model that he's used to create offline mapping files. We can continue to use that and just convert the maps to SCRIP map file format. In the longer term we want ESMF to be able to handle these grids, but we will have to solve the topology problems before we can give it to ESMF. Since, the ESMF team is overloaded right now, we'll get back to working on that aspect at a later date.

**Comment by ekluzek** [comment]
Closing this as we are handling it by having simple mesh files, coupled with mapping files.
