### ISSUE TITLE
Ticking time-bomb with #if ESMF_VERSION_MINOR > 0

### ISSUE THREAD

**Issue by aerorahul** [ESCOMP/CMEPS#105]
https://github.com/ESCOMP/CMEPS/blob/01dfe9a78af876fecfd3755a308161104e1c19b0/mediator/esmFlds.F90#L361

uh, does this make sense to anyone?
When ESMF releases 9.0.0 , this is going to blow!

Also, in several more places in https://github.com/ESCOMP/CMEPS/blob/master/mediator/esmFlds.F90

**Comment by rsdunlapiv** [comment]
Not sure, but it might be that @danrosen25 has already addressed by this in the HAFS work.  It is a problem for sure.

**Comment by billsacks** [comment]
It looks like this was fixed; closing.
