### ISSUE TITLE
latest med_fraction_mod needs fix for nems_orig_data  coupling mode

### ISSUE THREAD

**Issue by DeniseWorthen** [ESCOMP/CMEPS#112]
The nems_orig_data coupling mode was inadvertently left out of the coupling_mode statement for nems in updated med_fraction_mod.F90:

> if (trim(coupling_mode) == 'nems_orig' ) then

should be

> if (trim(coupling_mode) == 'nems_orig' .or. trim(coupling_mode) == 'nems_orig_data') then

**Comment by mvertens** [comment]
@DeniseWorthen - was this issue resolve. It seems identical to #113
