### ISSUE TITLE
Reference to runseq_NEMS

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CMEPS#147]
https://github.com/ESCOMP/CMEPS/blob/master/cime_config/buildnml#L402

The runseq_NEMS no longer exists.

**Comment by mvertens** [comment]
Why is this needed? We don't use NEMS with CIME at this point - they are using their own workflow?

**Comment by jedwards4b** [comment]
Right - the issue is that this did not get removed from buildnml

**Comment by mvertens** [comment]
Thanks for clarifying. I'll remove it in my next PR.

**Comment by mvertens** [comment]
Resolved in hash 5e99e9153d514fe0f64b6aceeb9b661cdcf193aa
