### ISSUE TITLE
Mesh files not handled by check_input_data

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CMEPS#196]
It looks like the various mesh files (mesh_atm, etc.) are not added to the files used by check_input_data. I *think* the issue is that blocks like this:

https://github.com/ESCOMP/CMEPS/blob/cf0d47ba7780783bdc812fb420322ce1b782b810/cime_config/namelist_definition_drv.xml#L1054-L1065

need an `input_pathname` element.

**Comment by mvertens** [comment]
@jedwards4b - can you please have a look at this.

**Comment by billsacks** [comment]
@jedwards4b @fischer-ncar - bumping this: it seems important to resolve with cmeps becoming the default driver.
