### ISSUE TITLE
memory leak in med_diag_mod.F90

### ISSUE THREAD

**Issue by mvertens** [ESCOMP/CMEPS#197]
There is a memory leak in med_diag_mod.F90.  When running the following test:
`
SMS_Ly1_Vnuopc.T62_g17.2000_DATM%NYF_SLND_DICE%SSMI_DOCN%DOM_DROF%NYF_SGLC_SWAV_SESP
`
Out of the box there are no diag calls in the run sequence and there is no memory leak that appears in the med.log file.
However, when the following calls are added to the run sequence
```
  MED med_phases_diag_atm
  MED med_phases_diag_rof
  MED med_phases_diag_accum
  MED med_phases_diag_print
```
A memory leak appears in the med.log file.

**Comment by jedwards4b** [comment]
fixed in #195
