### ISSUE TITLE
cmeps does not compile using gnu 10.1.0

### ISSUE THREAD

**Issue by DeniseWorthen** [ESCOMP/CMEPS#214]
Compiling ufs-weather model with GNU 10.1.0 fails. 

The full err.txt log is attached. The errors all seem to be either rank or type mismatches in ``util/shr_mpi_mod.F90``

[err.txt](https://github.com/ESCOMP/CMEPS/files/6849696/err.txt)

**Comment by jedwards4b** [comment]
For gnu 10 and newer you need additional compiler flags: 
 -fallow-argument-mismatch -fallow-invalid-boz 

 -fallow-argument-mismatch is needed for building with the mpich library with gfortran10;                                                                                
         -fallow-invalid-boz is needed for some components that have non-standard uses of BOZ literal constants with gfortran10 and newer.                                                 
         See https://github.com/ESMCI/cime/issues/3846 for details.

**Comment by DeniseWorthen** [comment]
Thanks @jedwards4b for the quick response.
