### ISSUE TITLE
Descriptions for flds_co2* fields isn't helpful, should tell user what they do

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CMEPS#245]
The descriptions for the flds_co2 fields in the namelist_definition_cesm.xml file are all the same and should be changed to describe what the fields actually do, in directing how CO2 is passed between components. The text just refers to the fact that these were changed from CPP tokens to namelist, but that change happened more than a decade ago, so it isn't useful anymore.

Here's the example for flds_co2a:

>       Previously, new fields that were needed to be passed between components
>       for certain compsets were specified by cpp-variables. This has been
>       modified to now be use cases. This use cases are specified in the
>       namelist cpl_flds_inparm and are currently triggered by the xml variable CCSM_BGC.
>       If CCSM_BGC is set to 'CO2A', then flds_co2a will be set to .true.

Do we agree this should be changed?

**Comment by ekluzek** [comment]
I suggest using the same wording I added to esmFldsExchange_cesm.F90 in my latest PR. So it would be something like:

> Pass CO2 from ATM to surface components

If that's acceptable, I can add this to my PR, should I do that?

**Comment by mvertens** [comment]
@ekluzek - yes, please add this to your PR. Thanks!
