### ISSUE TITLE
Number of drydep fields not initialized in seq_drydep_readnl

### ISSUE THREAD

**Issue by peverwhee** [ESCOMP/CMEPS#272]
In cesm/nuopc_cap_share/seq_drydep_mod.F90:

drydep_nflds not initialized and then conditionally incremented within seq_drydep_readnl

**Comment by gold2718** [comment]
This bug does not leave much of a trace. CESM log merely states:

> [0] (seq_drydep_init) Number of dry deposition fields transfered is **
> ================================================================================
> = BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
> = PID 117892 RUNNING AT i042.cgd.ucar.edu
> = EXIT CODE: 9
> = CLEANING UP REMAINING PROCESSES
> = YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
