### ISSUE TITLE
build workflow fails due to old version of ESMF

### ISSUE THREAD

**Issue by uturuncoglu** [ESCOMP/CMEPS#297]
The build workflow fails with following [PR](https://github.com/ESCOMP/CMEPS/pull/282) since it uses ESMF_XGridGet interface and I think it requires newer version of ESMF. I could able to compile it with esmf/8.3.0b09. @jedwards4b do you know which version is used by the build workflow? Is it possible to update it easily?

**Comment by uturuncoglu** [comment]
@jedwards4b I think the workflow is using `ESMF_8_2_0_beta_snapshot_14`

**Comment by jedwards4b** [comment]
#298 Should take care of the issue.

**Comment by jedwards4b** [comment]
Changing the ESMF build for this is easy.  Just edit this line: https://github.com/ESCOMP/CMEPS/blob/master/.github/workflows/extbuild.yml#L22  However note that in the PR ESMF is checked out directly from github and so the version looks like v8.3.0b13

**Comment by uturuncoglu** [comment]
@jedwards4b btw, I am not sure why it is failing if it points to `v8.3.0b13`.

**Comment by jedwards4b** [comment]
typo in the script...

**Comment by uturuncoglu** [comment]
I am not sure but the build workflow still picks `ESMF_VERSION: ESMF_8_2_0_beta_snapshot_14`. I could see it in the build log env I restart the all jobs. Any idea?
