### ISSUE TITLE
"RUN_TYPE=hybrid" not supported?

### ISSUE THREAD

**Issue by huitang-earth** [ESCOMP/CMEPS#302]
We had errors when running "hybrid" simulation using NUOPC. 

The model did not read restart file because `read_restart ` is set to `F`. This can be due to the following code, in which "hybrid" run is not considered. We are wondering if "hybrid" run are available using NUOPC and if so, how it can be done properly.

https://github.com/ESCOMP/CMEPS/blob/95e148bde5d71d31fd431f11a2539d461b325b9a/cesm/driver/ensemble_driver.F90#L163

**Comment by jedwards4b** [comment]
@huitang-earth sorry we missed this issue - the normal path to report problems like this is the cesm forum at
https://bb.cgd.ucar.edu/cesm/    
also hybrid runs work fine and are regularly tested with nuopc.
