### ISSUE TITLE
Better error message when CPL mismatch triggers an error

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CMEPS#328]
Users can create runs (notably short runs, but other cases may occur as well) where the user gets an error message like:

`20221205 161818.238 ERROR            PET11 src/addon/NUOPC/src/NUOPC_Base.F90:950 Invalid argument  - setClock timeStep=10800s is not a divisor of runDuration=16200s`

The current solution is to add :
`./xmlchange ROF_NCPL=\$ATM_NCPL`
`./xmlchange GLC_NCPL=\$ATM_NCPL`

The error message should include this solution as users are at a loss on how to solve this error with the current error message

**Comment by jedwards4b** [comment]
I suggest that this be trapped in the case.submit script and give an error message like the following:
`ERROR:  Runtime is shorter than the longest component coupling interval, increase runtime or increase ROF_NCPL and try again.`  Will that work for you?

**Comment by cacraigucar** [comment]
Can it give a little more information?  Could it say in addition:
Either increase Runtime to xxx or ROF_NCPL to yyy where xxx and yyy are the appropriate values.

Also, does GLC_NCPL not need to be changed?  We were told that GLC_NCPL also needed changing, but the one test case I looked at did not need changing, nor did you mention it in your error message.

**Comment by jedwards4b** [comment]
I've modified the message to read:

**Comment by cacraigucar** [comment]
> I've modified the message to read:

The rest was not written out?

**Comment by jedwards4b** [comment]
Oh and the message says ROF_NCPL because in this case that was the longest interval found - if LND had a longer coupling interval the message would say LND_NCPL.

**Comment by jedwards4b** [comment]
@cacraigucar don't rely on the email message - follow the link to the issue instead.

**Comment by cacraigucar** [comment]
Could the message include a number for the NCPL segment?

`ERROR: Runtime (9 s) is shorter than the longest component coupling interval (10800.0 s), increase runtime or increase ROF_NCPL to at least yyy and try again.` where yyy is determined by cime?

**Comment by jedwards4b** [comment]
Oh - I just realized a mistake - that's 9 steps not 9 seconds.    Again I don't think it wise to give such specific advice about the solution.

**Comment by jedwards4b** [comment]
https://github.com/ESMCI/cime/pull/4348

**Comment by jedwards4b** [comment]
Corrected error message:
`ERROR:  Runtime (16200.0 s) must be a multiple of the longest coupling interval ROF_NCPL (10800.0s).  Adjust runtime or ROF_NCPL`
