### ISSUE TITLE
LND2ROF_FMAPNAME and ROF2LND_FMAPNAME can be set in the XML for case -- but don't actually do anything

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CMEPS#346]
This is true in cmeps0.13.81. You can set LND2ROF_FMAPNAME and ROF2LND_FMAPNAME for a case, but they don't actually change the nupoc.runconfig to set the nuopc.runconfig configuration values: lnd2rof_map and rof2lnd_map. This obviously needs to be connected so that you can provide a mapping file for these cases. This is a critically important feature for working with mizuRoute.

**Comment by ekluzek** [comment]
It looks like this was broken with commit b4a19837

**Comment by billsacks** [comment]
Nice work tracking this down, @ekluzek !

**Comment by ekluzek** [comment]
I have a branch that we are testing that gets this to work for us. But, in the long-term I think this needs some discussion on the right way to do this. So I'm thinking that I should talk with @jedwards4b and @billsacks about this? Anyone else that should be involved? And should I just propose a meeting in the next few weeks?

**Comment by jedwards4b** [comment]
If you want these to work you just need to modify namelist_definition_drv.xml and add modify_via_xml="LND2ROF_FMAPNAME" and 
<value>$LND2ROF_FMAPNAME</value> 

you can look to ROF2OCN_FMAPNAME for an example.

**Comment by ekluzek** [comment]
@jedwards4b I have a simple fix along those lines that I'll submit a PR for. The larger thing that I'm concerned about is that there a bunch of XML variables that are disconnected from the namelist, so they do nothing. That's the bigger issue to discuss.  I'll create an issue for that as well.
