### ISSUE TITLE
problem in bilinear mapping generation with mediator runs on its own PEs

### ISSUE THREAD

**Issue by mvertens** [ESCOMP/CMEPS#35]
When I run the mediator on a disjoint set of processors from the rest of the components in an A compset, the atm->ice bilnr mapping crashes in the creation of the route handle. The conservative mapping route handle for atm->ice is fine.

Here is the reproducer for the problem
> git clone https://github.com/ESCOMP/UFSCOMP.git
> git checkout app_cesm-cmeps
> ./manage_externals/checkout_externals -v
> cd UFSCOMP/cime/scripts
> ./create_newcase --case /glade/scratch/oehmke/testseq_nuopc --compset A --res f19_g16_rx1 --driver nuopc --run-unsupported
> cd /glade/scratch/oehmke/testseq_nuopc
> ./xmlchange ROOTPE_ATM=4
> ./xmlchange ROOTPE_LND=8
> ./xmlchange ROOTPE_ICE=12
> ./xmlchange ROOTPE_OCN=16
> ./xmlchange ROOTPE_ROF=20
> ./xmlchange ROOTPE_GLC=24
> ./xmlchange ROOTPE_WAV=28
>  ./xmlchange ROOTPE_ESP=32
> ./case.setup
> ./case.build
> .case.submit 

To get the above to not crash you simply do the following:
> ./xmlchage ROOTPE_CPL=4
> ./case.setup --reset
> ./case.build
> ./case.submit

The error in the first case is:

```
20190930 112142.291 INFO             PET00  (module_med_map: RouteHandles_init) atm2ice_weights RH regrid for consf computed on the fly
20190930 112143.148 INFO             PET00  (module_med_map: RouteHandles_init) atm2ice_weights RH regrid for bilnr computed on the fly
20190930 112143.149 ERROR            PET00 /glade/u/home/dunlap/esmf/src/Infrastructure/Mesh/src/ESMCI_Mesh_Glue.C:5195 ESMCI_meshcreatedual() Internal error: Bad condition  - Condition {proc[i] < csize} failed at /glade/u/home/dunlap/esmf/src/Infrastructure/Mesh/src/Legacy/ESMCI_SparseMsg.C, line:67
20190930 112143.149 ERROR            PET00 ESMCI_MeshCap.C:1510 MeshCap::meshcreatedual() Internal error: Bad condition  - Internal subroutine call returned Error
20190930 112143.149 ERROR            PET00 ESMF_Mesh.F90:3633 ESMF_MeshCreateDual() Internal error: Bad condition  - Internal subroutine call returned Error
20190930 112143.149 ERROR            PET00 ESMF_FieldRegrid.F90:1110 ESMF_FieldRegridStoreNX Internal error: Bad condition  - Internal subroutine call returned Error
20190930 112143.149 ERROR            PET00 med_map_mod.F90:244 Internal error: Bad condition  - Passing error in return code
20190930 112143.149 ERROR            PET00 med.F90:1707 Internal error: Bad condition  - Passing error in return code
20190930 112143.149 ERROR            PET00 MED:src/addon/NUOPC/src/NUOPC_ModelBase.F90:549 Internal error: Bad condition  - Passing error in return code
```
This was caught running the scripts regression tests in CIME - the test is SEQ_Ln9.f19_g16_rx1.A.cheyenne_intel. So once this problem is fixed it would be useful to run this test to confirm that everything is still bfb when the processor layout is changed.

**Comment by billsacks** [comment]
Is this still an issue, or should it be closed?

**Comment by mvertens** [comment]
This has been fixed.
