### ISSUE TITLE
Ask for a specific version of ESMF in the CMake build.

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CMEPS#360]
Currently the CMake build just asks that a version of the ESMF library be found. This could be changed so that it asks for a specific version.

So this would change /CMakeLists.txt to have this...

`find_package(ESMF 8.4.1 REQUIRED)`

Rather than the current implementation where it says..

``` cmake
message("CMAKE_MODULE_PATH is ${CMAKE_MODULE_PATH}")

find_package(ESMF REQUIRED)
if (DEFINED PIO)
  set(PIO_PATH ${PIO})
else()

```

This would help prevent problems like this...

https://github.com/ESCOMP/CTSM/issues/1988

@jedwards4b @danrosen25 @billsacks please comment as you see fit...

**Comment by jedwards4b** [comment]
Yes we can add a check for ESMF version in the cmeps buildlib.

**Comment by jedwards4b** [comment]
This is already done in buildnml, we just need to update the minimum required version.
