### ISSUE TITLE
Add NaN checks for coupling fields

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CMEPS#370]
In the MCT-based CPL7, we had a subroutine that checked the fields sent between components and the coupler to detect NaN values and abort if any were found:

https://github.com/ESCOMP/CESM_CPL7andDataComps/blob/d16b2de2e759ab52b94cf0b17fa4f788931ecd4f/driver/main/component_type_mod.F90#L229-L263

@cacraigucar pointed out that we don't have a similar check in CMEPS, but would like to have one.

I talked a few weeks ago with members of the ESMF team. The feeling at that meeting was that, while long-term it could make sense to implement this inside ESMF itself, that would take a fair amount of work because of the need to do it in a general way that works for all systems. So the best near-term approach is probably to implement something like the above subroutine in CMEPS. A piece that could make this more challenging than in CPL7 is determining where this check should go - i.e., where we can intercept fields at the right point to do this check.

An alternative – less ideal but a possible fall-back if there isn't a good interception point in CMEPS – would be for components to add these checks in their caps. CTSM already does this, using this subroutine:

https://github.com/ESCOMP/CTSM/blob/0b98af47bcd307ca04ceaa0ed03c254d6be0344e/src/cpl/utils/lnd_import_export_utils.F90#L143-L167

so we could move that subroutine into a shared location so that other components could also call it from their caps. (The downsides of that approach are that it would require changes in all components that want it and it could lead to less consistency across the system in terms of when this is called.)

**Comment by billsacks** [comment]
I would be happy to take this issue, but it will probably be 2-3 weeks before I can commit to it, and then that is starting to get close to the time when I'll be unavailable for about a month (due to vacation and the CESM workshop). So I'm not sure I can promise to have it done in the time-frame in which @cacraigucar wants.

**Comment by mvertens** [comment]
@billsacks @jedwards4b - I think it will be fairly straightforward to implement this and I am happy to help. I think the right place to put this check is in the prep phase for each component. If you look at the cpl7 implementation the check is only made on the export fields from the coupler - not the import fields. The export fields are determined in each component's prep phase - so it would be easy to simply add a check in there.

**Comment by billsacks** [comment]
Thanks a lot, @mvertens ! My view is that it's probably sufficient to have this check on just one of the import or export fields to/from the mediator, like you say. I think having the local index and processor number is probably sufficient if it will be hard to get the global index. It seems like the important thing is to detect the existence of a NaN and print the name of the field that has this NaN value. But I'll let @cacraigucar chime in if she feels differently, since she raised this request.

**Comment by cacraigucar** [comment]
My biggest concern is to report the fieldname that contains the NaN, which this modification will be doing.  Fine tuning to the specific instance is an added bonus and what is proposed seems sufficient.  Thanks!
