### ISSUE TITLE
are the correct FBs being checked for in ocnalb routine?

### ISSUE THREAD

**Issue by DeniseWorthen** [ESCOMP/CMEPS#383]
Should the check here should be for the ocnalb_o and ocnalb_a FBs, not the aoflux FBs?

https://github.com/ESCOMP/CMEPS/blob/f2cbf27e4af63eb7edbf62aebc73608d271aab7e/mediator/med_phases_ocnalb_mod.F90#L278-L279

**Comment by mvertens** [comment]
@DeniseWorthen - there are no ocean albedos being sent directly to either the atm or the ocean. The albedos sent to the atm are merged albedos (e.g. Sx_anidf, etc)- so the only place ocean albedos are defined unique is in the FBMed_aoflux_a and FBMed_aoflux_o field bundles.

**Comment by DeniseWorthen** [comment]
@mvertens Thanks. The issue I'm having is that I want to turn on the ocean albedos on our side. I've actually be able to do this by calling the custom_cesm part of prep-ocn (otherwise I'd just need to duplicate a bunch of code inside custom_nems). But checking for the the aoflux bundles doesn't work for UFS, because we don't create those when we run the coupled model.

**Comment by mvertens** [comment]
@DeniseWorthen - thanks for the clarification. Lets talk so that I can see what you have done and if there is a more general way forwards.
