### ISSUE TITLE
Add an option to remove negative runoff by removing it evenly from positive runoff

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CMEPS#405]
In CESM, the land model can generate negative runoff for a variety of reasons. Ocean modelers tend not to like when the river model delivers negative runoff. So we are working to remove these sources of negative runoff, but it is very challenging to completely remove all sources of negative runoff locally in the land model, so we are exploring ways that we can remove any remaining negative runoff after the fact.

One thing we'd like to do is to add an option to CMEPS to remove negative runoff in the course of the rof-to-ocn mapping by setting negative runoff to 0 and decreasing all positive runoff proportionally so that the global runoff sum is still conserved. I think the implementation could be somewhat inspired by `med_phases_prep_glc_renormalize_smb`.

If there are no objections to this plan, I am tentatively planning to do the implementation sometime in the next few months. Please comment if you have any thoughts / objections.

@slevis-lmwg @swensosc please add any thoughts / corrections.

**Comment by mvertens** [comment]
@billsacks - thanks for taking this on. I'd like to be involved in the design process when you start this work.
