### ISSUE TITLE
When CISM is running in NOEVOLVE mode, we should still do MED -> GLC

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CMEPS#426]
In investigating https://github.com/ESCOMP/CISM-wrapper/issues/83 (leading to https://github.com/ESCOMP/CMEPS/pull/425), @Katec and I discovered that, when running CISM in NOEVOLVE mode, land fluxes currently aren't being remapped to the CISM / GLC grid. I assume this was done because @mvertens and I decided to set up the nuopc runsequence to not bother running GLC in a NOEVOLVE case (because you don't gain anything by running CISM in this case), and so it probably seemed logical to avoid the LND -> GLC remapping in this case as well. But in fact we want the LND -> GLC remapping to be done in this case, since a lot of the value of a NOEVOLVE case is to have the LND SMB fluxes remapped to the CISM grid.

Therefore, I propose changing the logic in runseq_TG.py and runseq_general.py so that med_phases_prep_glc and MED -> GLC are included whenever we're running with a non-stub glc.  (We still won't run GLC in noevolve mode.) To do this, I would rework the meaning of the run_glc and med_to_glc logicals in the python runsequence generation code; at first glance, I think the correct thing to do may be to swap the meaning of those two logicals, but I want to look more closely.

@mvertens - do you have any thoughts on this? I'm guessing you don't remember the details of this, but please let me know if you do remember something relevant or if you feel it's fine to go ahead with this proposed change.

@whlipscomb and @gunterl - FYI.

**Comment by billsacks** [comment]
@whlipscomb and @gunterl - I realized that the implication of this bug might not be clear from my original comment. To clarify: currently, in NOEVOLVE mode, we don't seem to be getting SMB fluxes remapped to the CISM grid.

**Comment by mvertens** [comment]
@billsacks - I haven't thought about this in a long time. I think your suggestion makes sense. It should be straightforward to test if this works correctly with that swap.
