### ISSUE TITLE
Modify output variable "U10" when add_gusts = .true.

### ISSUE THREAD

**Issue by megandevlan** [ESCOMP/CMEPS#438]
Following the addition of an option to add a convective-gust component to U10 over oceans (https://github.com/ESCOMP/CMEPS/pull/422), we changed the meaning of the U10 variable that's being sent from the coupler and output as "U10". It's now the large-scale wind (as was computed before) with the addition of gusts. We'd like to change the output such that the original U10 is still available, as is the U10 with gustiness. I'm following the approach laid out recently for a similar effort in E3SM (https://github.com/E3SM-Project/E3SM/commit/5813d4103bafda50840c7df8f87296872627f19c). Ultimately, two U10s will be defined - one resolved and one with the addition of gusts: 

```
aoflux_out%u10(n) = aoflux_out%u10res
aoflux_out%u10withGust(n) = sqrt(aoflux_out%duu10n(n))
```

I'm testing the approach now and will open a PR for this shortly.

**Comment by jedwards4b** [comment]
@megandevlan Is this issue resolved?  If so please close.

**Comment by megandevlan** [comment]
Thanks @jedwards4b  - all resolved.
