### ISSUE TITLE
Restart frequency of CICE inconsistent with other components 

### ISSUE THREAD

**Issue by gustavo-marques** [ESCOMP/CMEPS#459]
I am running out-of-the-box G cases using CESM_alpha17f. The issue can be reproduced using:
```
/glade/work/gmarques/cesm.sandboxes/cesm2_3_alpha17f/cime/scripts/create_newcase --case g.e23_a17f.GJRAv4.TL319_t232_zstar_N65.2024.056 --compset 2000_DATM%JRA-1p4-2018_SLND_CICE_MOM6_DROF%JRA-1p4-2018_SGLC_SWAV_SESP --res TL319_t232 --run-unsupported --driver nuopc
```

with the following modifications:

```
REST_OPTION  =   nyears
REST_N    =     5
```

CICE writes a restart and a rpointer every year, while the rest of the system writes them every 5 years. I only noticed this inconsistency because one of my cases was aborted in year 7 and when I re-submitted it, there was a mismatch in the clocks.

I'm cc'ing @dabail10 in case this issue should be moved to CICE.

**Comment by dabail10** [comment]
Ah, I think I know the problem. The internal namelist restart parameters for CICE is still active. I thought these were reset in the cap, but it is doing a force_restart_now. I know the fix. If you want a temporary solution set the following in user_nl_cice:

dumpfreq = 'x','x','x','x','x'

**Comment by dabail10** [comment]
This is fixed in cesm_cice6_5_0_12.
