### ISSUE TITLE
trigid commit breaks land regression tests for UFS

### ISSUE THREAD

**Issue by DeniseWorthen** [ESCOMP/CMEPS#475]
PR #470 breaks the ``atmlnd`` configuration baselines for UFS (``control_p8_atmlnd``). All compared field are different. 

The commit also breaks our comparisons for mediator restart and history files in multiple baselines because of an additional field present ``Med_frac_atm_lfrin``.

**Comment by mvertens** [comment]
@DeniseWorthen - I'm happy to help resolve this next week. The results should be bfb - however we can't really remove Med_frac_atm_lfrin at this point.
