### ISSUE TITLE
Very high resolutions need PIO to use the 64-bit data option (vs 64-bit offset mode)

### ISSUE THREAD

**Issue by briandobbins** [ESCOMP/CMEPS#491]
As the title says, the very high resolution runs often have single variables that exceed the limitations of the 64-bit 'offset' mode in NetCDF.

I'll submit a PR momentarily that just changes the default format to 64bit_data.

**Comment by billsacks** [comment]
Doing some cleanup... it looks like this was resolved with #492 so closing this (@briandobbins please reopen if I'm closing this incorrectly).
