### ISSUE TITLE
Make sure ROF runs after LND when ROF doesn't run as often as LND

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CMEPS#78]
As discussed in #57 we found that ROF currently seems to run before the LND component, and it needs to run afterwards. It looks correct when they are running at the same frequency, but when ROF doesn't run as often as LND (which is normally true) ROF runs first.

**Comment by mvertens** [comment]
@ekluzek - Thanks for pointing this out. Could you please clarify this. Should rof always run after the land? Even if everyone is at the same frequencey.

**Comment by ekluzek** [comment]
Yes, ROF should always run after land, since LND is the input to ROF. Looks like that is always what happens for the MCT driver. Note, there's some discussion on this at the end of #57.

**Comment by billsacks** [comment]
@ekluzek @mvertens has this been fixed or is it still an issue?

**Comment by ekluzek** [comment]
This appears to be correct now, looking at the latest externals update branch. So closing...
