### ISSUE TITLE
ESMF Verbosity

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CMEPS#79]
Cannot be set by CMEPS because ESMF is case sensitive and cime downcases its config variables.

**Comment by uturuncoglu** [comment]
I had a successful run with setting verbosity level. I'll create a dedicated PR for it. It will also includes changes for profiling attribute because attribute names are case sensitive. More information is in https://esmf-org.github.io/dev_docs/NUOPC_refdoc/node3.html#SECTION00033000000000000000
