### ISSUE TITLE
add new netcdf energy/water balance file to mediator output

### ISSUE THREAD

**Issue by mvertens** [ESCOMP/CMEPS#83]
There is an old branch - `mvertens/newdiags` that implemented the energy and water balance checks. This branch must be:

- [ ] merged to CMEPS master

- [ ] output to the med.log file must be changed so that a new netcdf file is created

- [ ] validation must be done and compared to the mct energy and water balance checks.

**Comment by billsacks** [comment]
@jedwards4b did this at some point.
